name: new_project
description: "A new Flutter project."
publish_to: "none"  # Ð£Ð±ÐµÐ¶Ð´Ð°ÐµÐ¼ÑÑ, Ñ‡Ñ‚Ð¾ Ð½Ðµ Ð¿ÑƒÐ±Ð»Ð¸ÐºÑƒÐµÐ¼ Ð² pub.dev

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.1  # ÐÐºÑ‚ÑƒÐ°Ð»ÑŒÐ½Ð°Ñ Ð²ÐµÑ€ÑÐ¸Ñ
  cloud_firestore: ^5.6.5
  firebase_auth: ^5.4.2  # Ð•ÑÐ»Ð¸ Ð½ÑƒÐ¶ÐµÐ½ Ð²Ñ…Ð¾Ð´ Ñ‡ÐµÑ€ÐµÐ· Firebase
  firebase_core_platform_interface: ^5.0.0
  image_picker: ^1.0.7  # ÐŸÐ¾ÑÐ»ÐµÐ´Ð½ÑÑ Ð²ÐµÑ€ÑÐ¸Ñ

  path_provider: ^2.1.2
  provider: ^6.1.1


  http: ^1.3.0
  flutter_markdown: ^0.7.6+2
  flutter_image: ^4.0.0  # ðŸ“Œ Ð”Ð¾Ð±Ð°Ð²Ð»ÑÐµÐ¼ Ð¿Ð¾Ð´Ð´ÐµÑ€Ð¶ÐºÑƒ Ð·Ð°Ð³Ñ€ÑƒÐ·ÐºÐ¸ Ð¸Ð·Ð¾Ð±Ñ€Ð°Ð¶ÐµÐ½Ð¸Ð¹
  firebase_storage: ^12.4.2
  image_picker_web: ^4.0.0
  firebase_core_web: ^2.21.1
  cloud_firestore_web: ^4.4.5
  build_runner: ^2.4.15


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  firebase_data_connect: any
  
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/NotoSans-Regular.ttf

  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
